# Generated by Django 4.1.3 on 2022-11-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_image_alter_ad_author_alter_ad_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
