# Generated by Django 4.1.3 on 2022-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='logos/logo.png', upload_to='logos/'),
        ),
    ]
